# Generated by Django 4.1.5 on 2024-02-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('online_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
